use std::sync::Arc;
use std::collections::HashSet;

use semantic_graph::prelude::*;
use crate::{VerificationLoop, VerificationEvent};

// ────────────────────────────────────────────────────────────
//  Constants
// ────────────────────────────────────────────────────────────

pub const SPREAD_RATE: f64 = 0.15;
pub const DECAY_GLOBAL: f64 = 0.97;
pub const BASE_INJECT: f64 = 0.4;
pub const ACTIVATION_MIN: f64 = 0.001;

/// Maximum edges to process for a single firing node during sparse spread.
/// Beyond this threshold, only the top N strongest edges receive energy.
pub const SPARSE_SPREAD_MAX_EDGES: usize = 64;

/// Minimum remaining energy threshold for sparse spread termination.
/// Propagation stops when remaining energy falls below this value.
pub const SPARSE_SPREAD_MIN_ENERGY: f64 = 0.005;

/// Capacity of the FiredNodesBuffer for event-driven STDP.
/// Must be ≥ max expected firing nodes per tick.
pub const FIRED_BUFFER_CAPACITY: usize = 1024;

/// Size of the working memory workspace ring buffer.
pub const WORKSPACE_CAPACITY: usize = 12;

/// Injection bonus for nodes currently in the workspace (sustained resonance).
pub const WORKSPACE_RESONANCE_INJECT: f64 = 0.15;

/// Number of consecutive ticks a StableBelief node must have high activation
/// before its energy can propagate to CoreConcept nodes.
pub const BELIEF_CONFIRMATION_TICKS: u8 = 5;

/// Activation threshold a StableBelief node must sustain to build confidence.
pub const BELIEF_CONFIRMATION_THRESHOLD: f64 = 0.7;

// ────────────────────────────────────────────────────────────
//  Types
// ────────────────────────────────────────────────────────────

/// Stack-allocated working memory workspace — preserves context across
/// multi-step inference chains without permanent consolidation.
///
/// Nodes pushed into the workspace represent the immediate focus of attention.
/// They receive sustained resonance injection (+0.15/tick) to resist decay.
/// Edges created between workspace nodes are marked TransientWorkspace and
/// bypassed during sleep consolidation.
pub struct WorkingMemoryWorkspace {
    pub slots: [NodeId; WORKSPACE_CAPACITY],
    pub count: usize,
}

impl WorkingMemoryWorkspace {
    pub fn new() -> Self {
        WorkingMemoryWorkspace {
            slots: [NodeId::ZERO; WORKSPACE_CAPACITY],
            count: 0,
        }
    }

    /// Push a node into the workspace (round-robin overwrite when full).
    pub fn push(&mut self, id: NodeId) {
        if self.count < WORKSPACE_CAPACITY {
            self.slots[self.count] = id;
            self.count += 1;
        } else {
            // Shift left, drop oldest, append newest
            for i in 1..WORKSPACE_CAPACITY {
                self.slots[i - 1] = self.slots[i];
            }
            self.slots[WORKSPACE_CAPACITY - 1] = id;
        }
    }

    /// Check if a node is currently in the workspace.
    pub fn contains(&self, id: NodeId) -> bool {
        self.slots[..self.count].contains(&id)
    }

    /// Clear the workspace.
    pub fn clear(&mut self) {
        self.count = 0;
    }
}

/// Result when a node crosses its threshold.
#[derive(Debug, Clone)]
pub struct FiredAction {
    pub node_id: NodeId,
    pub node_label: String,
    pub activation_level: f64,
    pub grounding: Grounding,
}

/// A render command generated by a fired motor effector node.
#[derive(Debug, Clone)]
pub struct RenderCommand {
    pub command_type: MotorCommandType,
    pub target: String,
    pub parameters: Vec<f64>,
    /// The predicted render hash (used for feedback comparison)
    pub predicted_hash: u64,
}

/// A render prediction for the feedback loop.
#[derive(Debug, Clone)]
pub struct RenderPrediction {
    pub effector_label: String,
    pub predicted_hash: u64,
    pub actual_hash: Option<u64>,
    pub error: Option<f64>,
}

/// The activation engine.
pub struct ActivationEngine {
    ctx: Arc<SemanticContext>,
    injection_queue: Vec<f64>,
    pub fired: Vec<FiredAction>,

    // ── Neuromodulation ──
    pub modulators: Neuromodulator,

    // ── STDP history ──
    pub firing_history: FiringHistory,

    // ── Predictive coding ──
    /// Predicted activation for each node (computed during Phase 3 of previous tick).
    predictions: Vec<f64>,

    /// Prediction errors detected this tick (consumed by daemon after tick).
    pub prediction_errors: Vec<PredictionError>,

    // ── Structural verification ──
    /// Faults detected by the verification loop during the last tick.
    pub structural_faults: Vec<VerificationEvent>,

    // ── Render feedback loop ──
    /// Render commands produced by motor effectors that fired this tick.
    pub pending_render_commands: Vec<RenderCommand>,
    /// Render predictions awaiting feedback (used for prediction error checks).
    pub render_predictions: Vec<RenderPrediction>,

    // ── Visual effector buffer (lock-free, shared with render bridge) ──
    /// Optional lock-free buffer for pushing effector commands to the render bridge.
    pub effector_buffer: Option<Arc<VisualEffectorBuffer>>,

    // ── Visual primitive ring buffer (lock-free SPSC, shared with render bridge) ──
    /// Optional lock-free ring buffer for streaming FixedVisualPayload
    /// to the render bridge when visual primitive cluster activation exceeds threshold.
    pub visual_ring: Option<Arc<VisualPrimitiveRingBuffer>>,

    // ── Staging arrays (pre-allocated, zero alloc in hot path) ──
    /// Which nodes fired this tick (bitset, parallel to firing_history words)
    fired_this_tick: Vec<u64>,

    // ── Event-driven STDP: FiredNodesBuffer ──
    /// Fixed-capacity buffer of fired node indices for Phase 4.
    /// During Phase 3, when a node fires, its index is pushed here.
    /// Phase 4 uses this to iterate only incident edges instead of
    /// the full graph O(N+E) — critical for high-degree hub nodes.
    fired_nodes_buffer: [u32; FIRED_BUFFER_CAPACITY],
    /// Number of valid entries in fired_nodes_buffer.
    fired_nodes_count: usize,

    // ── Working Memory Workspace ──
    /// Stack-allocated ring buffer of the current focus of attention.
    pub workspace: WorkingMemoryWorkspace,

    // ── Epistemic belief tracking ──
    /// Confidence level for each StableBelief node (0.0 = no confidence, 1.0 = confirmed).
    belief_confidence: Vec<f64>,
    /// Consecutive ticks each StableBelief node has been above threshold.
    belief_streak: Vec<u8>,
    /// Cached epistemic status for each node (updated at start of Phase 2).
    /// Used by Phase 3 spread to gate TransientObservation→CoreConcept and
    /// StableBelief→CoreConcept energy propagation without graph locks.
    node_epistemic: Vec<EpistemicStatus>,

    // ── Counterfactual simulation mode ──
    /// When `Counterfactual`, Phase 4 (STDP) and Phase 5 (valence) are short-circuited.
    pub cognitive_mode: CognitiveMode,
}

impl ActivationEngine {
    pub fn new(
        ctx: Arc<SemanticContext>,
        effector_buffer: Option<Arc<VisualEffectorBuffer>>,
        visual_ring: Option<Arc<VisualPrimitiveRingBuffer>>,
    ) -> Self {
        let len = ctx.graph.read().len().max(64);
        let words = (len + 63) / 64;
        ActivationEngine {
            injection_queue: vec![0.0; len],
            fired: Vec::with_capacity(16),
            modulators: Neuromodulator::new(),
            firing_history: FiringHistory::new(len),
            predictions: vec![0.0; len],
            prediction_errors: Vec::with_capacity(4),
            structural_faults: Vec::with_capacity(2),
            pending_render_commands: Vec::with_capacity(8),
            render_predictions: Vec::with_capacity(8),
            effector_buffer,
            visual_ring,
            fired_this_tick: vec![0; words.max(1)],
            fired_nodes_buffer: [0u32; FIRED_BUFFER_CAPACITY],
            fired_nodes_count: 0,
            workspace: WorkingMemoryWorkspace::new(),
            belief_confidence: vec![0.0; len],
            belief_streak: vec![0u8; len],
            node_epistemic: vec![EpistemicStatus::CoreConcept; len],
            cognitive_mode: CognitiveMode::Actual,
            ctx,
        }
    }

    /// Inject activation energy into a specific node.
    pub fn inject(&mut self, target: NodeId, energy: f64) {
        let idx = target.0 as usize;
        if idx < self.injection_queue.len() {
            self.injection_queue[idx] += energy;
        }
    }

    /// Inject energy into all nodes in a CD frame's role slots.
    pub fn inject_frame(&mut self, frame: &ConceptualFrame, base_energy: f64) {
        for (node_id, energy) in frame.injection_targets(base_energy) {
            self.inject(node_id, energy);
        }
    }

    /// Spike a neuromodulator channel (called from daemon).
    pub fn spike_novelty(&mut self, amount: f64) { self.modulators.spike_novelty(amount); }
    pub fn spike_arousal(&mut self, amount: f64) { self.modulators.spike_arousal(amount); }
    pub fn spike_reward(&mut self, amount: f64) { self.modulators.spike_reward(amount); }

    // ── Full 4-phase tick ──────────────────────────────────

    pub fn tick(&mut self) -> &[FiredAction] {
        self.fired.clear();
        self.prediction_errors.clear();
        self.structural_faults.clear();
        self.pending_render_commands.clear();
        self.ctx.tick.fetch_add(1, std::sync::atomic::Ordering::Relaxed);

        let graph = self.ctx.graph.read();
        let node_count = graph.len();

        // Ensure buffers are large enough (cold path if resized)
        if self.injection_queue.len() < node_count {
            self.injection_queue.resize(node_count, 0.0);
            self.predictions.resize(node_count, 0.0);
            self.firing_history.resize(node_count);
            let new_words = (node_count + 63) / 64;
            self.fired_this_tick.resize(new_words.max(1), 0);
        }

        let mut act_guard = self.ctx.activation.write();
        let activations = act_guard.back_mut();

        if activations.len() < node_count {
            drop(act_guard);
            drop(graph);
            let mut act_guard2 = self.ctx.activation.write();
            let activations2 = act_guard2.back_mut();
            for i in activations2.len()..node_count {
                if i < activations2.len() {
                    activations2[i] = 0.0;
                }
            }
            return &self.fired;
        }

        // ──────────────────────────────────────────────────
        //  Phase 1 — Neuromodulator decay
        // ──────────────────────────────────────────────────
        self.modulators.tick_decay();
        let threshold_mod = self.modulators.threshold_modifier();
        let plasticity_mod = self.modulators.plasticity_modifier();

        // ──────────────────────────────────────────────────
        //  Phase 2 — Decay + Injection + Prediction Error
        //            + Workspace Resonance + Belief Tracking
        // ──────────────────────────────────────────────────
        for i in 1..node_count {
            let node = match graph.get(NodeId::from_raw(i as u64)) {
                Some(n) => n.read(),
                None => continue,
            };

            let mut a = activations[i];
            let node_epistemic = node.epistemic_status;

            // Cache epistemic status for zero-lock Phase 3 gating
            self.node_epistemic[i] = node_epistemic;

            // Node-specific decay followed by global decay
            a *= node.decay * DECAY_GLOBAL;

            // Add injected energy from external events
            a += self.injection_queue[i];

            // ── Workspace sustained resonance ──
            // Nodes in the current workspace receive a small energy injection
            // every tick, preventing them from decaying into silence. This
            // preserves context across multi-step inference chains.
            if self.workspace.contains(NodeId::from_raw(i as u64)) {
                a += WORKSPACE_RESONANCE_INJECT;
            }

            // Floor to prevent noise accumulation
            if a < ACTIVATION_MIN {
                a = 0.0;
            }

            // ── Belief confidence tracking ──
            // StableBelief nodes accumulate confidence when their activation
            // stays above threshold. Once confirmed for BELIEF_CONFIRMATION_TICKS
            // consecutive ticks, they can spread to CoreConcept nodes.
            if node_epistemic == EpistemicStatus::StableBelief {
                if a > BELIEF_CONFIRMATION_THRESHOLD {
                    let streak = &mut self.belief_streak[i];
                    *streak = (*streak + 1).min(BELIEF_CONFIRMATION_TICKS);
                    self.belief_confidence[i] = *streak as f64 / BELIEF_CONFIRMATION_TICKS as f64;
                } else {
                    self.belief_streak[i] = 0;
                    self.belief_confidence[i] = 0.0;
                }
            }

            // ── Prediction error check (precision-weighted) ──
            let predicted = self.predictions[i];
            if predicted > ACTIVATION_MIN {
                let raw_error = (a - predicted).abs() / predicted.max(ACTIVATION_MIN);

                // Drop read lock before acquiring write lock for variance update
                drop(node);
                let (new_var, weighted_error) = if let Some(n) = graph.get(NodeId::from_raw(i as u64)) {
                    let mut w = n.write();
                    let old_var = w.variance;
                    let old_mean = w.mean_error;
                    let new_mean = old_mean + 0.05 * (raw_error - old_mean);
                    let sq_err = (a - predicted).powi(2);
                    let new_var = old_var + 0.05 * (sq_err - old_var);
                    w.mean_error = new_mean;
                    w.variance = new_var;
                    let precision = (1.0 / (new_var + 0.001)).clamp(0.1, 10.0);
                    (new_var, raw_error * precision)
                } else {
                    (0.0, raw_error)
                };
                let _ = new_var;

                if weighted_error > PREDICTION_ERROR_THRESHOLD {
                    self.prediction_errors.push(PredictionError {
                        node_id: NodeId::from_raw(i as u64),
                        expected: predicted,
                        actual: a,
                        error_magnitude: weighted_error,
                    });
                    self.modulators.spike_novelty(weighted_error * 0.15);
                }
            } else {
                drop(node);
            }

            activations[i] = a;
        }

        // ── Measure total energy before spread (for conservation check) ──
        let mut energy_before_spread: f64 = 0.0;
        for i in 1..node_count {
            energy_before_spread += activations[i].abs();
        }

        // ──────────────────────────────────────────────────
        //  Phase 3 — Spreading activation + eligibility
        // ──────────────────────────────────────────────────
        //
        //  Clear fired_this_tick bitset for the current tick
        self.clear_fired_bitset();

        for i in 1..node_count {
            let a_i = activations[i];
            if a_i.abs() < ACTIVATION_MIN {
                continue;
            }

            let node = match graph.get(NodeId::from_raw(i as u64)) {
                Some(n) => n.read(),
                None => continue,
            };

            // ── Threshold check (modulated by neuromodulators) ──
            let effective_threshold = node.threshold * threshold_mod;
            if a_i > effective_threshold {
                // Node fires this tick
                let grounding = node.grounding.clone();
                self.fired.push(FiredAction {
                    node_id: NodeId::from_raw(i as u64),
                    node_label: node.label.clone(),
                    activation_level: a_i,
                    grounding: grounding.clone(),
                });

                // ── Push to FiredNodesBuffer for event-driven Phase 4 ──
                if self.fired_nodes_count < FIRED_BUFFER_CAPACITY {
                    self.fired_nodes_buffer[self.fired_nodes_count] = i as u32;
                    self.fired_nodes_count += 1;
                }

                // ── Render feedback loop: if MotorCommand, record render command ──
                if let Grounding::MotorCommand { command_type, ref target, ref parameters } = grounding {
                    let predicted_hash = (command_type.label().len() as u64)
                        .wrapping_mul(target.len() as u64)
                        .wrapping_add(parameters.len() as u64);
                    self.pending_render_commands.push(RenderCommand {
                        command_type,
                        target: target.clone(),
                        parameters: parameters.clone(),
                        predicted_hash,
                    });
                    self.render_predictions.push(RenderPrediction {
                        effector_label: node.label.clone(),
                        predicted_hash,
                        actual_hash: None,
                        error: None,
                    });
                }

                // Record in bitset
                self.set_fired_bit(i);

                // Record in ring buffer
                self.firing_history.record_fired(NodeId::from_raw(i as u64));

                // Consume all energy on fire (no spread from fired node)
                activations[i] = 0.0;
                continue;
            }

            // ── Sparse spread to neighbors ──
            let edge_count = node.edges.len();
            if edge_count > SPARSE_SPREAD_MAX_EDGES {
                // High-degree node: sort edges by weight and only spread to top N
                let mut sorted: Vec<(usize, f64)> = node.edges.iter().enumerate()
                    .map(|(idx, e)| (idx, e.effective_weight()))
                    .collect();
                sorted.sort_unstable_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

                let mut remaining = a_i;
                for (idx, _w) in sorted.iter().take(SPARSE_SPREAD_MAX_EDGES) {
                    if remaining.abs() < SPARSE_SPREAD_MIN_ENERGY {
                        break;
                    }
                    let edge = &node.edges[*idx];
                    let target_idx = edge.target.0 as usize;
                    if target_idx >= node_count {
                        continue;
                    }
                    // Epistemic gate: observations cannot directly activate CoreConcept;
                    // beliefs need sufficient confidence to propagate to CoreConcept.
                    if self.node_epistemic[target_idx] == EpistemicStatus::CoreConcept {
                        let src_epi = self.node_epistemic[i];
                        if src_epi == EpistemicStatus::TransientObservation {
                            continue;
                        }
                        if src_epi == EpistemicStatus::StableBelief
                            && self.belief_confidence[i] < BELIEF_CONFIRMATION_THRESHOLD
                        {
                            continue;
                        }
                    }
                    let spread_energy = remaining * edge.effective_weight() * SPREAD_RATE;
                    activations[target_idx] += spread_energy;
                    remaining -= spread_energy;
                }
                activations[i] = remaining;
            } else {
                // Normal-degree node: iterate all edges
                for edge in &node.edges {
                    let target_idx = edge.target.0 as usize;
                    if target_idx >= node_count {
                        continue;
                    }
                    // Epistemic gate: observations cannot directly activate CoreConcept;
                    // beliefs need sufficient confidence to propagate to CoreConcept.
                    if self.node_epistemic[target_idx] == EpistemicStatus::CoreConcept {
                        let src_epi = self.node_epistemic[i];
                        if src_epi == EpistemicStatus::TransientObservation {
                            continue;
                        }
                        if src_epi == EpistemicStatus::StableBelief
                            && self.belief_confidence[i] < BELIEF_CONFIRMATION_THRESHOLD
                        {
                            continue;
                        }
                    }
                    let spread_energy = a_i * edge.effective_weight() * SPREAD_RATE;
                    activations[target_idx] += spread_energy;
                    activations[i] -= spread_energy;
                }
            }
        }

        // ── Measure total energy after spread (for conservation check) ──
        let mut energy_after_spread: f64 = 0.0;
        for i in 1..node_count {
            energy_after_spread += activations[i].abs();
        }

        // ── Compute next-tick predictions from current activation levels ──
        // Prediction = what activation we expect next tick (after decay + injection)
        for i in 1..node_count {
            self.predictions[i] = activations[i];
        }

        // ──────────────────────────────────────────────────
        //  Phase 4 — Event-driven STDP + pruning
        // ──────────────────────────────────────────────────
        //
        //  In Counterfactual mode, STDP is short-circuited — no weight changes
        //  are applied. This allows the system to simulate "what if" scenarios
        //  without altering long-term memory.
        if self.cognitive_mode == CognitiveMode::Counterfactual {
            self.fired_nodes_count = 0;
            // Skip Phase 4 entirely — no STDP during counterfactual simulation.
        } else {
        //
        //  Instead of iterating all edges (O(N+E) global), we use
        //  the FiredNodesBuffer to process only edges incident to
        //  nodes that fired this tick. For each fired node:
        //    1. Process outbound edges (eligibility decay, LTP)
        //    2. Scan inbound edges from other fired nodes (LTP)
        //    3. LTD drift + mark for pruning
        //
        //  This is O(F * avg_degree) instead of O(N + E), critical
        //  when a high-degree hub like SELF has thousands of edges.

        let mut prune_targets: Vec<(usize, usize)> = Vec::with_capacity(16);
        let mut processed_pairs: HashSet<(usize, usize)> = HashSet::new();
        let fired_count = self.fired_nodes_count;

        for fn_idx in 0..fired_count {
            let i = self.fired_nodes_buffer[fn_idx] as usize;
            if i >= node_count || i == 0 {
                continue;
            }

            // ── Outbound edges from fired node i ──
            let node = match graph.get(NodeId::from_raw(i as u64)) {
                Some(n) => n.write(),
                None => continue,
            };

            for (edge_idx, edge) in node.edges.iter_mut().enumerate() {
                // Skip TransientWorkspace edges — they are ephemeral associations
                // that should not undergo STDP or be consolidated.
                if edge.contract == InvariantContract::TransientWorkspace {
                    continue;
                }

                // Eligibility decay
                edge.eligibility *= ELIGIBILITY_DECAY;

                // Boost when source (i) fired this tick
                edge.eligibility += 1.0;

                // LTP: if target fired this tick, consume eligibility
                let target_idx = edge.target.0 as usize;

                // Check if target was in this tick's fired set
                let target_fired = if target_idx < node_count {
                    self.is_fired_this_tick(target_idx)
                } else {
                    false
                };

                if target_fired {
                    let delta = edge.eligibility * LTP_RATE * plasticity_mod;
                    edge.dynamic_weight = (edge.dynamic_weight + delta).clamp(-1.0, 1.0);
                    edge.eligibility *= 0.5;
                    processed_pairs.insert((i, target_idx));
                }

                // LTD drift toward default weight
                let default_w = edge.weight_override.unwrap_or_else(|| edge.relation.spread_weight());
                edge.dynamic_weight += (default_w - edge.dynamic_weight) * DRIFT_RATE;
                edge.dynamic_weight = edge.dynamic_weight.clamp(-1.0, 1.0);

                // Mark for pruning if weight fell below threshold
                if edge.dynamic_weight.abs() < PRUNE_THRESHOLD {
                    prune_targets.push((i, edge_idx));
                    edge.dynamic_weight = 0.0;
                }
            }

            // ── Inbound edges from other fired nodes → LTP ──
            // Scan backward through the buffer to find pairs (j→i) where
            // j also fired this tick and we haven't processed (j,i) yet.
            for fn_j in 0..fn_idx {
                let j = self.fired_nodes_buffer[fn_j] as usize;
                if j == i || j >= node_count {
                    continue;
                }
                if processed_pairs.contains(&(j, i)) {
                    continue; // already handled by outbound processing
                }

                // Check if j has an edge to i
                let got = graph.get(NodeId::from_raw(j as u64));
                if let Some(guard) = got {
                    let mut n = guard.write();
                    for edge in &mut n.edges {
                        if edge.target.0 as usize == i {
                            let delta = edge.eligibility * LTP_RATE * plasticity_mod;
                            edge.dynamic_weight = (edge.dynamic_weight + delta).clamp(-1.0, 1.0);
                            edge.eligibility *= 0.5;
                            processed_pairs.insert((j, i));
                        }
                    }
                }
            }
        }

        // ⎯⎯  LTD drift for all nodes (lightweight, just weight drift) ──
        // Scan any nodes that had edges updated during pruning
        for (node_idx, edge_idx) in &prune_targets {
            if let Some(node_lock) = graph.get(NodeId::from_raw(*node_idx as u64)) {
                let mut node = node_lock.write();
                if *edge_idx < node.edges.len() {
                    node.edges[*edge_idx].dynamic_weight = 0.0;
                }
            }
        }

        } // end else (STDP active)

        // Reset FiredNodesBuffer for next tick
        self.fired_nodes_count = 0;

        // ──────────────────────────────────────────────────
        //  Phase 5 — Valence update (preference formation)
        // ──────────────────────────────────────────────────
        //
        //  In Counterfactual mode, valence is NOT updated — no preferences
        //  are altered during "what if" simulation.
        //
        //  Nodes that fire without prediction error → positive valence (familiar = good).
        //  Nodes involved in prediction errors → negative valence (surprise = aversive).
        //  SELF drifts slowly upward (baseline contentment).
        //  Over time, this creates genuine preferences — the system "likes" what it
        //  can predict and "dislikes" what surprises it.

        if self.cognitive_mode == CognitiveMode::Counterfactual {
            // Skip Phase 5 entirely — no valence changes during counterfactual simulation.
        } else {

        let reward_level = self.modulators.reward;

        // Build set of node IDs with prediction errors this tick
        let mut error_nodes: Vec<usize> = self.prediction_errors.iter()
            .map(|e| e.node_id.0 as usize)
            .collect();
        error_nodes.sort();
        error_nodes.dedup();

        for action in &self.fired {
            let idx = action.node_id.0 as usize;
            let in_error = error_nodes.binary_search(&idx).is_ok();
            if in_error {
                // Negative: surprise is aversive
                graph.update_valence(action.node_id, -0.3, 0.05);
            } else {
                // Positive: familiar patterns feel good
                let pos_target = 0.2 + reward_level * 0.3;
                graph.update_valence(action.node_id, pos_target, 0.02);
            }
        }

        // Nodes that received injection but didn't fire: mild positive (being noticed)
        for i in 1..node_count {
            if self.injection_queue[i] > 0.0 {
                let id = NodeId::from_raw(i as u64);
                let already_fired = self.fired.iter().any(|f| f.node_id == id);
                if !already_fired {
                    graph.update_valence(id, 0.1, 0.01);
                }
            }
        }

        // SELF baseline: slow drift toward positive
        graph.update_valence(NodeId::SELF, 0.5, 0.001);

        } // end else (valence update active)

        // ── Phase 6 — Structural verification ──
        let fired_chain: Vec<NodeId> = self.fired.iter().map(|f| f.node_id).collect();
        self.structural_faults = VerificationLoop::verify(
            &self.ctx,
            &mut self.modulators,
            energy_before_spread,
            energy_after_spread,
            &fired_chain,
        );

        // Penalize valence on nodes involved in structural faults
        for fault in &self.structural_faults {
            if let VerificationEvent::StructuralFault { ref error, ref penalties } = fault {
                for action in &self.fired {
                    graph.update_valence(action.node_id, -penalties.valence_drop, 0.1);
                }
                match error {
                    StructuralError::ContractMismatch { source, target, .. } => {
                        // Mark the offending edge for pruning
                        if let Some(node) = graph.get(*source) {
                            let mut n = node.write();
                            for edge in &mut n.edges {
                                if edge.target == *target {
                                    edge.dynamic_weight = 0.0;
                                }
                            }
                        }
                    }
                    _ => {}
                }
            }
        }

        // ── Push effector state to VisualEffectorBuffer (lock-free) ──
        if let Some(ref buffer) = self.effector_buffer {
            let state = self.compute_effector_state(&self.fired);
            buffer.write(&state);
        }

        // ── Phase 6: Extract visual primitives → push to SPSC ring buffer ──
        if let Some(ref ring) = self.visual_ring {
            let payload = self.ctx.graph.read()
                .get_active_visual_primitives(activations);
            if payload.cluster_activation() > VISUAL_CLUSTER_THRESHOLD {
                ring.push(&payload);
            }
        }

        // ── Advance firing history ring buffer ──
        self.firing_history.advance_tick();

        // ── Zero out injection queue for next tick ──
        for i in 1..node_count {
            self.injection_queue[i] = 0.0;
        }

        // ── Flip double buffer ──
        act_guard.flip();

        &self.fired
    }

    // ── Effector state computation ──────────────────────

    /// Compute a [f32; 22] effector state from the fired action list.
    ///
    /// Iterates fired nodes with MotorCommand grounding and accumulates
    /// activation-weighted transform parameters into the 22-element
    /// state array. Kinetic/spatial activation is derived from
    /// MotorCommand type frequency: DrawSkeleton fires boost kinetic,
    /// ApplyMesh fires boost spatial.
    ///
    /// Lock-free: called from the cognitive tick hot path
    /// and written atomically into VisualEffectorBuffer.
    fn compute_effector_state(&self, fired: &[FiredAction]) -> [f32; EFFECTOR_STATE_FLOATS] {
        let mut state = [0.0f32; EFFECTOR_STATE_FLOATS];
        let mut kinetic_total: f32 = 0.0;
        let mut spatial_total: f32 = 0.0;
        let mut motor_count: usize = 0;

        for action in fired {
            if let Grounding::MotorCommand { command_type, ref parameters, .. } = &action.grounding {
                let act = action.activation_level as f32;
                motor_count += 1;
                match command_type {
                    MotorCommandType::ApplyTransform => {
                        // Accumulate rotation angles from transform parameters (radians)
                        for (j, p) in parameters.iter().enumerate().take(6) {
                            state[j] = state[j] + act * (*p as f32);
                        }
                        kinetic_total += act * 0.6;
                    }
                    MotorCommandType::DrawSkeleton => {
                        // Accumulate scale from parameters
                        if parameters.len() >= 3 {
                            state[14] += act * parameters[0] as f32;
                            state[15] += act * parameters[1] as f32;
                            state[16] += act * parameters[2] as f32;
                        }
                        state[20] += act; // bone_twist modifier
                        kinetic_total += act * 0.8;
                    }
                    MotorCommandType::ApplyMesh => {
                        // Color intensity from mesh parameters
                        if let Some(c) = parameters.first() {
                            state[6] += act * (*c as f32); // color_r0
                            state[10] += act * (*c as f32 * 0.5); // color_r1
                        }
                        spatial_total += act * 0.7;
                    }
                    MotorCommandType::Composite => {
                        // Blend weight from composite commands
                        state[17] += act * 0.3;
                        spatial_total += act * 0.3;
                    }
                    _ => {}
                }
            }
        }

        // Clamp all values to prevent unbounded accumulation
        for val in state.iter_mut() {
            *val = val.clamp(-10.0, 10.0);
        }

        // Derive color palette from kinetic/spatial totals
        let kinetic_blend = if motor_count > 0 {
            (kinetic_total / motor_count as f32 * 0.8 + 0.2).clamp(0.0, 1.0)
        } else {
            0.5
        };
        let spatial_blend = if motor_count > 0 {
            (spatial_total / motor_count as f32 * 0.8 + 0.2).clamp(0.0, 1.0)
        } else {
            0.5
        };
        effector_state::set_color0(&mut state, kinetic_blend, spatial_blend * 0.5, 0.3, 1.0);
        effector_state::set_color1(&mut state, 0.3, 0.5, spatial_blend, kinetic_blend);
        effector_state::set_palette_coeffs(&mut state, kinetic_blend, spatial_blend);

        state
    }

    // ── Bitset helpers ──────────────────────────────────

    #[inline]
    fn set_fired_bit(&mut self, node_idx: usize) {
        let word = node_idx / 64;
        let bit = node_idx % 64;
        if word < self.fired_this_tick.len() {
            self.fired_this_tick[word] |= 1u64 << bit;
        }
    }

    #[inline]
    fn is_fired_this_tick(&self, node_idx: usize) -> bool {
        let word = node_idx / 64;
        let bit = node_idx % 64;
        word < self.fired_this_tick.len() && (self.fired_this_tick[word] & (1u64 << bit)) != 0
    }

    #[inline]
    fn clear_fired_bitset(&mut self) {
        for w in &mut self.fired_this_tick {
            *w = 0;
        }
    }

    /// Get the current activation levels (for monitoring / debug UI).
    pub fn read_activations(&self) -> Vec<(NodeId, f64)> {
        let act = self.ctx.activation.read();
        let snapshot = act.read();
        snapshot.iter().enumerate().skip(1).map(|(i, &v)| (NodeId::from_raw(i as u64), v)).collect()
    }

    /// Current neuromodulator levels (for debug/bridge).
    pub fn read_modulators(&self) -> (f64, f64, f64) {
        (self.modulators.novelty, self.modulators.arousal, self.modulators.reward)
    }

    // ── Working Memory Workspace ────────────────────────

    /// Push a node into the working memory workspace.
    /// Nodes in the workspace receive sustained resonance injection.
    pub fn push_workspace(&mut self, id: NodeId) {
        self.workspace.push(id);
    }

    /// Clear the working memory workspace.
    pub fn clear_workspace(&mut self) {
        self.workspace.clear();
    }

    /// Check if a node is currently in the workspace.
    pub fn in_workspace(&self, id: NodeId) -> bool {
        self.workspace.contains(id)
    }

    /// Create an edge between two workspace nodes marked TransientWorkspace.
    /// These edges are ephemeral — they bypass STDP and are dropped during
    /// consolidation.
    pub fn link_workspace(&mut self, source: NodeId, target: NodeId, relation: Relation) {
        self.ctx.graph.link_workspace_edge(source, target, relation);
    }

    /// Returns current workspace nodes as a slice.
    pub fn workspace_snapshot(&self) -> &[NodeId] {
        &self.workspace.slots[..self.workspace.count]
    }

    // ── Cognitive Mode ──────────────────────────────────

    /// Set the cognitive mode (Actual or Counterfactual).
    /// In Counterfactual mode, Phase 4 (STDP) and Phase 5 (valence) are
    /// short-circuited, allowing "what if" simulation without long-term effects.
    pub fn set_mode(&mut self, mode: CognitiveMode) {
        self.cognitive_mode = mode;
    }

    /// Get the current cognitive mode.
    pub fn mode(&self) -> CognitiveMode {
        self.cognitive_mode
    }

    // ── Render feedback loop ─────────────────────────────

    /// Process render feedback: compare actual render state hash against
    /// predictions. Updates prediction errors and spikes reward/novelty.
    ///
    /// Call this when the renderer sends back the result of a render command.
    /// The actual_hash should be computed by the renderer based on what was
    /// actually rendered.
    pub fn process_render_feedback(&mut self, effector_label: &str, actual_hash: u64) {
        let mut matched = false;

        for pred in &mut self.render_predictions {
            if pred.effector_label == effector_label {
                pred.actual_hash = Some(actual_hash);

                if actual_hash == pred.predicted_hash {
                    // Render matched prediction → reward spike
                    pred.error = Some(0.0);
                    self.modulators.spike_reward(0.05);
                    matched = true;
                } else {
                    // Render mismatch → prediction error + novelty
                    let error_mag = if pred.predicted_hash == 0 {
                        1.0
                    } else {
                        // Normalized difference between expected and actual
                        let diff = if actual_hash > pred.predicted_hash {
                            actual_hash - pred.predicted_hash
                        } else {
                            pred.predicted_hash - actual_hash
                        };
                        (diff as f64 / pred.predicted_hash.max(1) as f64).min(1.0)
                    };
                    pred.error = Some(error_mag);
                    self.prediction_errors.push(PredictionError {
                        node_id: NodeId::ZERO,
                        expected: pred.predicted_hash as f64,
                        actual: actual_hash as f64,
                        error_magnitude: error_mag,
                    });
                    self.modulators.spike_novelty(error_mag * 0.15);
                }
                break;
            }
        }

        // Clean up matched predictions (keep unresolved ones)
        self.render_predictions.retain(|p| p.actual_hash.is_none());
    }

    /// Clear all pending render predictions (called when renderer resets).
    pub fn clear_render_predictions(&mut self) {
        self.render_predictions.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_graph() -> GraphArena {
        let mut g = GraphArena::with_capacity(16);

        g.insert(GroundedNode {
            id: NodeId::ZERO,
            label: "sensor_motion".into(),
            node_type: NodeType::Sensor,
            grounding: Grounding::Sensor {
                sensor_type: "accelerometer".into(),
                channel: 0,
                norm: SensorNorm::Linear { scale: 0.1, offset: 0.0 },
            },
            decay: 0.8,
            threshold: 2.0,
            base_activation: 0.0,
            edges: vec![Edge::new(Relation::Activates, NodeId::from_raw(2))],
            epistemic_status: EpistemicStatus::CoreConcept,
            valence: 0.0,
            mean_error: 0.0,
            variance: 0.0,
        });

        g.insert(GroundedNode {
            id: NodeId::ZERO,
            label: "concept_movement".into(),
            node_type: NodeType::Concept,
            grounding: Grounding::Abstract,
            decay: 0.9,
            threshold: 1.5,
            base_activation: 0.0,
            edges: vec![Edge::new(Relation::Implies, NodeId::from_raw(3))],
            epistemic_status: EpistemicStatus::CoreConcept,
            valence: 0.0,
            mean_error: 0.0,
            variance: 0.0,
        });

        g.insert(GroundedNode {
            id: NodeId::ZERO,
            label: "action_notify".into(),
            node_type: NodeType::Action,
            grounding: Grounding::Action {
                intent_template: r#"{"action":"notify_movement","params":{}}"#.into(),
            },
            decay: 0.5,
            threshold: 1.0,
            base_activation: 0.0,
            edges: Vec::new(),
            epistemic_status: EpistemicStatus::CoreConcept,
            valence: 0.0,
            mean_error: 0.0,
            variance: 0.0,
        });

        g
    }

    #[test]
    fn activation_propagates_and_fires() {
        let graph = test_graph();
        let ctx = SemanticContext::new(graph);
        let mut engine = ActivationEngine::new(ctx.clone(), None, None);

        engine.inject(NodeId::from_raw(1), 2.5);

        for _ in 0..10 {
            let fired = engine.tick();
            if !fired.is_empty() {
                assert_eq!(fired[0].node_label, "action_notify");
                return;
            }
        }
        panic!("No action fired within 10 ticks");
    }

    #[test]
    fn energy_decays_to_zero() {
        let graph = test_graph();
        let ctx = SemanticContext::new(graph);
        let mut engine = ActivationEngine::new(ctx.clone(), None, None);

        engine.inject(NodeId::from_raw(1), 0.3);

        let mut max_seen = 0.0;
        for _ in 0..30 {
            let _fired = engine.tick();
            let activations = engine.read_activations();
            let max = activations.iter().map(|(_, v)| *v).fold(0.0_f64, f64::max);
            max_seen = max_seen.max(max);
            if max < ACTIVATION_MIN {
                return;
            }
        }
        panic!("Energy did not decay to zero within 30 ticks (last max: {:.6})", max_seen);
    }

    #[test]
    fn activation_reads_after_tick() {
        let graph = test_graph();
        let ctx = SemanticContext::new(graph);
        let mut engine = ActivationEngine::new(ctx.clone(), None, None);
        engine.inject(NodeId::from_raw(1), 0.5);
        let _fired = engine.tick();
        let activations = engine.read_activations();
        assert!(!activations.is_empty(), "should have activation readings");
        assert_eq!(activations[0].0, NodeId::from_raw(1));
    }

    #[test]
    fn stdp_strengthens_cofiring_edge() {
        let mut graph = GraphArena::with_capacity(16);
        // Node 2 and 3 where 2→3 has an edge
        let mut n2 = GroundedNode {
            id: NodeId::ZERO,
            label: "trigger".into(),
            node_type: NodeType::Concept,
            grounding: Grounding::Abstract,
            decay: 0.9,
            threshold: 0.5,
            base_activation: 0.0,
            edges: vec![Edge::new(Relation::Activates, NodeId::from_raw(3))],
            epistemic_status: EpistemicStatus::CoreConcept,
            valence: 0.0,
            mean_error: 0.0,
            variance: 0.0,
        };
        let n3 = GroundedNode {
            id: NodeId::ZERO,
            label: "target".into(),
            node_type: NodeType::Concept,
            grounding: Grounding::Abstract,
            decay: 0.9,
            threshold: 1.5,
            base_activation: 0.0,
            edges: Vec::new(),
            epistemic_status: EpistemicStatus::CoreConcept,
            valence: 0.0,
            mean_error: 0.0,
            variance: 0.0,
        };
        graph.insert(n3);

        let ctx = SemanticContext::new(graph);
        let mut engine = ActivationEngine::new(ctx.clone(), None, None);

        let initial_weight = engine.ctx.graph.read()
            .get(NodeId::from_raw(2)).unwrap().read()
            .edges[0].dynamic_weight;

        // Inject so both fire: trigger gets 2.0, target gets 2.0
        engine.inject(NodeId::from_raw(2), 2.0);
        engine.inject(NodeId::from_raw(3), 2.0);

        for _ in 0..3 {
            engine.tick();
        }

        let post_weight = engine.ctx.graph.read()
            .get(NodeId::from_raw(2)).unwrap().read()
            .edges[0].dynamic_weight;

        // Edge should be reinforced from co-firing
        assert!(post_weight > initial_weight,
            "STDP should strengthen co-firing edge: {:.6} -> {:.6}", initial_weight, post_weight);
    }

    #[test]
    fn prediction_error_spikes_novelty() {
        let graph = test_graph();
        let ctx = SemanticContext::new(graph);
        let mut engine = ActivationEngine::new(ctx.clone(), None, None);

        // First tick establishes a prediction baseline
        engine.inject(NodeId::from_raw(1), 2.5);
        engine.tick();

        let novelty_before = engine.modulators.novelty;

        // Second tick with zero injection → prediction will be wrong (expects energy, gets none)
        engine.inject(NodeId::from_raw(1), 0.0);
        engine.tick();

        let novelty_after = engine.modulators.novelty;
        assert!(novelty_after > novelty_before,
            "Prediction error should increase novelty: {:.6} -> {:.6}", novelty_before, novelty_after);
    }

    #[test]
    fn neuromodulator_threshold_modulation() {
        let mut graph = GraphArena::with_capacity(16);
        let node = GroundedNode {
            id: NodeId::ZERO,
            label: "hard_to_fire".into(),
            node_type: NodeType::Concept,
            grounding: Grounding::Abstract,
            decay: 0.9,
            threshold: 5.0,  // high threshold
            base_activation: 0.0,
            edges: Vec::new(),
            epistemic_status: EpistemicStatus::CoreConcept,
            valence: 0.0,
            mean_error: 0.0,
            variance: 0.0,
        };
        graph.insert(node);
        let ctx = SemanticContext::new(graph);
        let mut engine = ActivationEngine::new(ctx.clone(), None, None);

        // Inject below threshold (4.0 < 5.0), should not fire without neuromodulation
        engine.inject(NodeId::from_raw(2), 4.0);
        let fired = engine.tick();
        assert!(fired.is_empty(), "Should not fire without modulation");

        // Now spike novelty to lower effective threshold
        engine.spike_novelty(1.0);
        engine.inject(NodeId::from_raw(2), 4.0);
        let fired2 = engine.tick();

        // With novelty=1.0, threshold_mod = 1.0 - 0.35 = 0.65
        // effective_threshold = 5.0 * 0.65 = 3.25
        // 4.0 > 3.25 → should fire
        assert!(!fired2.is_empty(), "Should fire with high novelty modulation");
    }
}
